autoInstallPeers: false

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msgpackr-extract

peerDependencyRules:
  allowAny:
    - '*'
  ignoreMissing:
    - '*'

publicHoistPattern:
  - '*@biomejs/biome*'
